AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "tui-backend"
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      ClusterName: "tui-cluster"
Outputs:
  RepoName:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/{ECRRepository}"
    Export:
      Name: 'RepoName'
    Description: Repository Name