AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties: 
    RepositoryName: "tui-backend"
Outputs:
  RepoName:
    Value: !Ref "ECRRepository"
    Export:
      Name: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/testsimran"
    Description: Repository Name